[package]
name = "up-all"
version = "0.0.1"
authors = ["Joseph Levine <adauctus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
